"""add ingestion batch and level title

Revision ID: 14cd5701c9fb
Revises: 390d23f60e64
Create Date: 2026-05-30 18:23:23.519833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14cd5701c9fb"
down_revision: Union[str, None] = "390d23f60e64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_batch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_raw_text", sa.Text(), nullable=True),
        sa.Column("media_urls", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("item_group", sa.Column("ingestion_batch_id", sa.Uuid(), nullable=True))
    op.add_column("item_group", sa.Column("level_title", sa.String(length=50), nullable=True))
    op.create_index(
        op.f("ix_item_group_ingestion_batch_id"), "item_group", ["ingestion_batch_id"], unique=False
    )
    op.create_foreign_key(
        "fk_item_group_ingestion_batch_id",
        "item_group",
        "ingestion_batch",
        ["ingestion_batch_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_item_group_ingestion_batch_id", "item_group", type_="foreignkey")
    op.drop_index(op.f("ix_item_group_ingestion_batch_id"), table_name="item_group")
    op.drop_column("item_group", "level_title")
    op.drop_column("item_group", "ingestion_batch_id")
    op.drop_table("ingestion_batch")
    # ### end Alembic commands ###
