"""learner correction_level

Revision ID: 7dcdea84e87e
Revises: e8b3f51a2c47
Create Date: 2026-06-11 22:27:40.308304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dcdea84e87e"
down_revision: Union[str, None] = "e8b3f51a2c47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learner",
        sa.Column(
            "correction_level",
            sa.String(length=16),
            server_default=sa.text("'gentle'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learner", "correction_level")
    # ### end Alembic commands ###
