"""Add last_active_learner_id to account

Revision ID: 856696040434
Revises: 37f5422ffdbf
Create Date: 2026-04-25 22:36:03.756632

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "856696040434"
down_revision: str | None = "37f5422ffdbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("last_active_learner_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "account", "learner", ["last_active_learner_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "account", type_="foreignkey")
    op.drop_column("account", "last_active_learner_id")
    # ### end Alembic commands ###
