"""add learner persona

Revision ID: a50676ada60e
Revises: c9e4f72a1d38
Create Date: 2026-05-06 23:00:03.307937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a50676ada60e"
down_revision: Union[str, None] = "c9e4f72a1d38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learner",
        sa.Column(
            "ai_name", sa.String(length=100), server_default=sa.text("'Tina'"), nullable=False
        ),
    )
    op.add_column(
        "learner",
        sa.Column(
            "ai_gender", sa.String(length=10), server_default=sa.text("'female'"), nullable=False
        ),
    )
    op.add_column("learner", sa.Column("ai_persona_prompt", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learner", "ai_persona_prompt")
    op.drop_column("learner", "ai_gender")
    op.drop_column("learner", "ai_name")
    # ### end Alembic commands ###
