"""create content model

Revision ID: b46a6684d7e9
Revises: a50676ada60e
Create Date: 2026-05-15 22:42:38.855640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46a6684d7e9'
down_revision: Union[str, None] = 'a50676ada60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('anchor', sa.String(length=200), nullable=False),
    sa.Column('cefr_level', sa.String(length=4), nullable=True),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'text', name='uq_language_item_type_text')
    )
    op.create_table('item_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_account_id', sa.Uuid(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('prompt_notes', sa.Text(), nullable=True),
    sa.Column('source_book_hint', sa.String(length=200), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['item_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_group_owner_account_id'), 'item_group', ['owner_account_id'], unique=False)
    op.create_index(op.f('ix_item_group_parent_id'), 'item_group', ['parent_id'], unique=False)
    op.create_table('learner_item_stats',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('seen_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['language_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id', 'item_id')
    )
    op.create_table('item_group_member',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['item_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['language_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'item_id')
    )
    op.add_column('learner', sa.Column('cefr_level', sa.String(length=4), nullable=True))
    op.add_column('session', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'session', 'item_group', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'group_id')
    op.drop_column('learner', 'cefr_level')
    op.drop_table('item_group_member')
    op.drop_table('learner_item_stats')
    op.drop_index(op.f('ix_item_group_parent_id'), table_name='item_group')
    op.drop_index(op.f('ix_item_group_owner_account_id'), table_name='item_group')
    op.drop_table('item_group')
    op.drop_table('language_item')
    # ### end Alembic commands ###
