"""group share link + adoption tables

Revision ID: c62cb152ead5
Revises: 8f2d4b7c1a90
Create Date: 2026-06-11 11:20:46.880377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c62cb152ead5"
down_revision: Union[str, None] = "8f2d4b7c1a90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_adoption",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_group_id", sa.Uuid(), nullable=True),
        sa.Column("target_group_id", sa.Uuid(), nullable=False),
        sa.Column("adopted_by_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["adopted_by_account_id"], ["account.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_group_id"], ["item_group.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_group_id"], ["item_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_group_id"),
    )
    op.create_table(
        "group_share_link",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_account_id"], ["account.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["item_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_group_share_link_group_id"), "group_share_link", ["group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_share_link_group_id"), table_name="group_share_link")
    op.drop_table("group_share_link")
    op.drop_table("group_adoption")
    # ### end Alembic commands ###
