"""add curriculum system

Revision ID: d9ecc84cd217
Revises: c9e4f72a1d38
Create Date: 2026-05-06 17:02:32.562075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9ecc84cd217"
down_revision: Union[str, None] = "c9e4f72a1d38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("text", sa.String(length=200), nullable=False),
        sa.Column("anchor", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "text", name="uq_language_item_type_text"),
    )
    op.create_table(
        "curriculum",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("owner_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_account_id"], ["account.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "learner_item_stats",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("seen_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("used_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("correct_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["language_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learner.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("learner_id", "item_id"),
    )
    op.create_table(
        "curriculum_unit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("unit_number", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["curriculum_id"], ["curriculum.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curriculum_unit_curriculum_id"), "curriculum_unit", ["curriculum_id"], unique=False
    )
    op.create_table(
        "curriculum_lesson",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("prompt_notes", sa.Text(), nullable=True),
        sa.Column("focus_instructions", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["curriculum_unit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curriculum_lesson_unit_id"), "curriculum_lesson", ["unit_id"], unique=False
    )
    op.create_table(
        "learner_lesson",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["learner.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lesson_id"], ["curriculum_lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("learner_id", "lesson_id"),
    )
    op.create_table(
        "lesson_item",
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["language_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lesson_id"], ["curriculum_lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("lesson_id", "item_id"),
    )
    op.add_column("session", sa.Column("lesson_id", sa.Uuid(), nullable=True))
    op.add_column("session", sa.Column("collection_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "session", "curriculum_lesson", ["lesson_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "session", type_="foreignkey")
    op.drop_column("session", "collection_id")
    op.drop_column("session", "lesson_id")
    op.drop_table("lesson_item")
    op.drop_table("learner_lesson")
    op.drop_index(op.f("ix_curriculum_lesson_unit_id"), table_name="curriculum_lesson")
    op.drop_table("curriculum_lesson")
    op.drop_index(op.f("ix_curriculum_unit_curriculum_id"), table_name="curriculum_unit")
    op.drop_table("curriculum_unit")
    op.drop_table("learner_item_stats")
    op.drop_table("curriculum")
    op.drop_table("language_item")
    # ### end Alembic commands ###
