"""add turn

Revision ID: dc5311592f26
Revises: 856696040434
Create Date: 2026-04-30 15:44:30.877009

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc5311592f26"
down_revision: str | None = "856696040434"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turn",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("text_user", sa.Text(), nullable=False),
        sa.Column("text_ai", sa.Text(), nullable=False),
        sa.Column("audio_in_path", sa.String(length=512), nullable=True),
        sa.Column("audio_out_path", sa.String(length=512), nullable=True),
        sa.Column("stt_audio_seconds", sa.Float(), server_default="0", nullable=False),
        sa.Column("llm_input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("llm_output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tts_chars", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["learner.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turn_learner_id"), "turn", ["learner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turn_learner_id"), table_name="turn")
    op.drop_table("turn")
    # ### end Alembic commands ###
