"""add session

Revision ID: e30514cd95f2
Revises: dc5311592f26
Create Date: 2026-04-30 17:10:46.021668

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e30514cd95f2"
down_revision: str | None = "dc5311592f26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["learner.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_learner_id"), "session", ["learner_id"], unique=False)
    op.add_column("turn", sa.Column("session_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_turn_session_id"), "turn", ["session_id"], unique=False)
    op.create_foreign_key(None, "turn", "session", ["session_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "turn", type_="foreignkey")
    op.drop_index(op.f("ix_turn_session_id"), table_name="turn")
    op.drop_column("turn", "session_id")
    op.drop_index(op.f("ix_session_learner_id"), table_name="session")
    op.drop_table("session")
    # ### end Alembic commands ###
